# syntax=docker/dockerfile:1

FROM node:16-alpine

WORKDIR /imi-module-selection/api

ENV NODE_ENV=development

COPY package*.json ./

RUN npm install -g nodemon && npm install

EXPOSE 3000

CMD ["nodemon"]
