version: '3'
services:
  node-server:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - 3000:3000
    container_name: node-server
    depends_on:
      - mongo-db
    volumes:
      - .:/imi-module-selection/api
      - /imi-module-selection/client
      - /imi-module-selection/api/node_modules

  vue-app:
    build:
      context: client/
      dockerfile: Dockerfile-dev
    ports:
      - 8080:8080
    container_name: vue-app
    depends_on:
      - node-server
    volumes:
      - ./.eslintrc.js:/imi-module-selection/app/.eslintrc.js
      - ./client:/imi-module-selection/app
      - /imi-module-selection/app/node_modules
  
  mongo-db:
    image: mongo
    ports: 
      - 27017:27017
    container_name: mongo-db
    volumes:
      - ./docker-dev-db:/data/db
